const {ErroCampus}=require('./campusContexto');
const {validarContexto}=require('../utils/campusQuery');
const bcrypt=require('bcryptjs');
const PADRAO={logo_tamanho:'M',logo_posicao:'esquerda',nome_tamanho:'auto',fonte:'sans',escala_fonte:'M',logo_aniversario_url:null};
function verificar(r){if(r.error)throw new ErroCampus(503,'kids_config_indisponivel','Não foi possível consultar a configuração deste campus.');return r.data;}
async function senhaConfig(db,ctx){validarContexto(ctx);return verificar(await db.from('kids_totem_config_campus').select('edit_senha_hash').eq('igreja_id',ctx.campus_id).maybeSingle());}
async function statusSenha(db,ctx){return {definida:!!(await senhaConfig(db,ctx))?.edit_senha_hash};}
async function verificarSenha(db,ctx,senha){const c=await senhaConfig(db,ctx);if(!c?.edit_senha_hash)return {ok:false,naoDefinida:true};if(typeof senha!=='string'||senha.length>128)return {ok:false};return {ok:await bcrypt.compare(senha,c.edit_senha_hash)};}
async function salvarSenha(db,ctx,senha,usuarioId){validarContexto(ctx,true);if(typeof senha!=='string'||senha.length<4||senha.length>128)throw new ErroCampus(400,'kids_senha_invalida','Use uma senha entre 4 e 128 caracteres.');const agora=new Date().toISOString();verificar(await db.from('kids_totem_config_campus').upsert({igreja_id:ctx.campus_id,edit_senha_hash:await bcrypt.hash(senha,10),edit_senha_por:usuarioId,edit_senha_em:agora,updated_at:agora},{onConflict:'igreja_id'}));return {ok:true};}
async function etiqueta(db,ctx){validarContexto(ctx);return verificar(await db.from('kids_etiqueta_config_campus').select('logo_tamanho,logo_posicao,nome_tamanho,fonte,escala_fonte,logo_aniversario_url').eq('igreja_id',ctx.campus_id).maybeSingle())||{...PADRAO};}
async function salvarEtiqueta(db,ctx,body){validarContexto(ctx,true);const opcoes={logo_tamanho:['P','M','G'],logo_posicao:['esquerda','direita','acima'],nome_tamanho:['auto','P','M','G'],fonte:['sans','condensada','arredondada','serif','mono'],escala_fonte:['P','M','G','GG']};const patch={igreja_id:ctx.campus_id,updated_at:new Date().toISOString()};for(const [key,values] of Object.entries(opcoes)){if(body[key]===undefined)continue;if(!values.includes(body[key]))throw new ErroCampus(400,'kids_layout_invalido','Opção de layout inválida.');patch[key]=body[key];}verificar(await db.from('kids_etiqueta_config_campus').upsert(patch,{onConflict:'igreja_id'}));return etiqueta(db,ctx);}
async function logo(db,ctx,dataUrl){validarContexto(ctx,true);const m=String(dataUrl||'').match(/^data:(image\/(png|jpe?g|webp));base64,([A-Za-z0-9+/=]+)$/);if(!m)throw new ErroCampus(400,'kids_logo_invalida','Imagem inválida.');const buffer=Buffer.from(m[3],'base64');if(!buffer.length||buffer.length>3*1024*1024)throw new ErroCampus(413,'kids_logo_grande','Use uma imagem de até 3 MB.');const ext=m[1].includes('png')?'png':m[1].includes('webp')?'webp':'jpg';const path=`kids-logos/${ctx.campus_id}/aniversario.${ext}`;verificar(await db.storage.from('fotos-membros').upload(path,buffer,{contentType:m[1],upsert:true}));const {data}=db.storage.from('fotos-membros').getPublicUrl(path);if(!data?.publicUrl)throw new Error('Logo indisponível.');const url=`${data.publicUrl}?t=${Date.now()}`;verificar(await db.from('kids_etiqueta_config_campus').upsert({igreja_id:ctx.campus_id,logo_aniversario_url:url,updated_at:new Date().toISOString()},{onConflict:'igreja_id'}));return {logo_aniversario_url:url};}
async function removerLogo(db,ctx){validarContexto(ctx,true);verificar(await db.from('kids_etiqueta_config_campus').upsert({igreja_id:ctx.campus_id,logo_aniversario_url:null,updated_at:new Date().toISOString()},{onConflict:'igreja_id'}));verificar(await db.storage.from('fotos-membros').remove(['png','jpg','webp'].map(ext=>`kids-logos/${ctx.campus_id}/aniversario.${ext}`)));return {ok:true};}
async function reservarCodigos(db,ctx,body,usuarioId){validarContexto(ctx,true);const quantidade=body.quantidade===undefined?60:Number(body.quantidade);if(!Number.isInteger(quantidade)||quantidade<1||quantidade>200)throw new ErroCampus(400,'kids_reserva_invalida','Reserve entre 1 e 200 códigos.');const r=await db.rpc('fn_campus_kids_reservar_codigos',{p_igreja_id:ctx.campus_id,p_usuario_id:usuarioId,p_estacao_ref:body.estacao_ref,p_sessao_id:body.sessao_id,p_quantidade:quantidade,p_estacao_id:body.estacao_id||null});if(r.error)throw new ErroCampus(r.error.code==='23514'?409:503,'kids_reserva_recusada',r.error.code==='23514'?r.error.message:'Não foi possível reservar códigos agora.');if(!Array.isArray(r.data))throw new Error('Bloco de códigos indisponível.');const codigos=r.data.map(r=>r.codigo);return {codigos,total:codigos.length,estacao_ref:body.estacao_ref};}
module.exports={statusSenha,verificarSenha,salvarSenha,etiqueta,salvarEtiqueta,logo,removerLogo,reservarCodigos};
