// @vitest-environment node
import { describe,it,expect,vi } from 'vitest';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const {criarGestaoBatismoApp}=require('../../backend/services/campusBatismoGestaoApp');
const A='00000000-0000-0000-0000-000000000001',B='00000000-0000-0000-0000-000000000002',U='00000000-0000-0000-0000-000000000003',I='00000000-0000-0000-0000-000000000004';
function banco(){
 const rows:any={profiles:[{id:U,active:true,is_diretoria_geral:false}],app_campus_config:[{id:true,estado:'ativo',campus_legado_id:A}],igrejas:[{id:A,ativa:true,tipo:'sede'},{id:B,ativa:true,tipo:'sede'}],app_super_admins:[],usuario_igrejas:[{usuario_id:U,igreja_id:A}],batismo_inscricoes:[{id:I,igreja_id:A,membro_id:U,status:'pendente',deleted_at:null,data_batismo:'2099-09-27',codigo_acesso:'segredo',codigo_conferencia:'segredo'}]};
 const calls:any[]=[];const db:any={rows,calls,from:(table:string)=>{const call:any={table,filters:[],single:false};calls.push(call);const q:any={};for(const op of ['select','order','range'])q[op]=()=>q;for(const op of ['eq','is','not'])q[op]=(...args:any[])=>{call.filters.push([op,...args]);return q;};q.maybeSingle=()=>{call.single=true;return q;};q.then=(ok:any,no:any)=>{let data=(rows[table]||[]).filter((r:any)=>call.filters.every(([op,k,v]:any[])=>op==='not'?!['cancelado','rejeitado'].includes(r[k]):r[k]===v));return Promise.resolve({data:call.single?data[0]||null:data,error:null}).then(ok,no);};return q;}};return db;
}
const req={user:{id:U,email:'pessoa@test.com',user_metadata:{is_super_admin:true}},method:'GET',headers:{'x-campus-id':A}};
const ctx={campus_id:A,campi:[{id:A,tipo:'sede'}],estado:'ativo',campus_legado_id:A};
function criar(db:any,extras:any={}){return criarGestaoBatismoApp({db,permissao:async()=>({leitura:2,escrita:2,superadmin:false}),eventos:async()=>[{id:B,data:'2099-09-27'}],horarios:async()=>[],...extras});}
describe('gestão de Batismo no App exige papel e campus ERP',()=>{
 it('papel Batismo não concede acesso ao campus público B; metadata não eleva acesso',async()=>{const db=banco();await expect(criar(db).acesso({...req,headers:{'x-campus-id':B}})).rejects.toMatchObject({status:403,codigo:'campus_acesso_negado'});expect(db.calls.some((c:any)=>c.table==='usuario_igrejas')).toBe(true);});
 it('nega membro sem papel antes de ler dados de gestão',async()=>{const db=banco();await expect(criar(db,{permissao:async()=>({leitura:1,escrita:1})}).acesso(req)).rejects.toMatchObject({status:403});expect(db.calls).toHaveLength(0);});
 it('nega perfil inativo e preserva vínculo explícito de campus',async()=>{const db=banco();expect((await criar(db).acesso(req)).ctx.campus_id).toBe(A);db.rows.profiles[0].active=false;await expect(criar(db).acesso(req)).rejects.toMatchObject({status:403});});
 it('lista só atos locais e retira códigos secretos da projeção',async()=>{const db=banco();db.rows.batismo_inscricoes.push({...db.rows.batismo_inscricoes[0],id:B,igreja_id:B});const result=await criar(db).listar(ctx);expect(result.pessoas).toHaveLength(1);expect(result.aprovacoes).toHaveLength(1);expect(result.pessoas[0]).not.toHaveProperty('codigo_acesso');expect(db.calls.filter((c:any)=>c.table==='batismo_inscricoes').every((c:any)=>c.filters.some((f:any[])=>f[1]==='igreja_id'&&f[2]===A))).toBe(true);});
 it('criação usa reservador e nunca aceita membro ou campus do cliente',async()=>{const db=banco(),salvar=vi.fn().mockResolvedValue({id:I});await criar(db,{salvar}).criar(ctx,{membro_id:B,igreja_id:B,nome:'Pessoa',sobrenome:'Teste',data_batismo:'2099-09-27'},U);expect(salvar).toHaveBeenCalledWith(db,ctx,expect.not.objectContaining({membro_id:B}),{usuarioId:U});expect(salvar.mock.calls[0][2]).toMatchObject({status:'confirmado',origem:'app_gestao_batismo'});});
 it('editar ID de outro campus não chama reservador; edição própria mantém flag interna',async()=>{const db=banco(),salvar=vi.fn();await expect(criar(db,{salvar}).editar({...ctx,campus_id:B,campi:[{id:B}]},I,{},U)).rejects.toMatchObject({status:404});expect(salvar).not.toHaveBeenCalled();await criar(db,{salvar}).editar(ctx,I,{nome:'Novo',status:'cancelado'},U);expect(salvar.mock.calls[0][2]).toEqual({nome:'Novo'});expect(salvar.mock.calls[0][3]).toMatchObject({editarDadosPessoa:true,usuarioId:U,atual:{id:I,igreja_id:A}});});
 it('cancelamento passa pela reserva e mantém o histórico',async()=>{const db=banco(),salvar=vi.fn();expect(await criar(db,{salvar}).retirar(ctx,I,U)).toEqual({ok:true,id:I});expect(salvar.mock.calls[0][2]).toEqual({status:'cancelado'});});
});
