-- ============================================================================
-- Logística · Estoque · seed do catálogo (260 produtos · do SharePoint GestaodeEstoque)
-- ============================================================================
-- SEM saldo (decisão do Marcos): a igreja faz o inventário físico e lança como
-- os primeiros movimentos no sistema. valor_unitario + quantidade_minima vêm do
-- Power App (config · ajustável). controla_validade=true p/ Alimentos e Bebidas.
-- Idempotente via ON CONFLICT no nome (lower/btrim).
-- ============================================================================
BEGIN;
INSERT INTO public.log_estoque_produtos
  (nome, categoria, subtipo_infra, valor_unitario, quantidade_minima, controla_validade)
VALUES
  ('AÇÚCAR SACHE CAIXA COM 400 UND', 'Alimentos', NULL, 31.78, 2, true),
  ('ADOÇANTE ZERO CAL 100ML', 'Alimentos', NULL, 6.09, 3, true),
  ('CAFÉ TRADICIONAL MELITTA 500G', 'Bebidas', NULL, 30.77, 20, true),
  ('CÁLICE PARA SANTA CEIA CAIXA COM 48 UND', 'Ministerial', NULL, 46, 24, false),
  ('FILTRO CAFÉ DE PAPEL 103', 'Descartáveis', NULL, 4.5, 6, false),
  ('MEXEDOR DE CAFÉ GRANDE PACOTE COM 500 UND', 'Descartáveis', NULL, 10.9, 4, false),
  ('MEXEDOR DE CAFÉ GRANDE PACOTE COM 200 UND', 'Descartáveis', NULL, 9.4, 5, false),
  ('BALA JUQUINHA 300G', 'Alimentos', NULL, 17.98, 0, true),
  ('BOLINHO SB 35G GOTAS', 'Alimentos', NULL, 1.39, 0, true),
  ('CHOCOLATE BIS', 'Alimentos', NULL, 10.4, 0, true),
  ('MILHO DE PIPOCA 500G', 'Alimentos', NULL, 3.99, 3, true),
  ('ROLO DE ETIQUETAS', 'Ministerial', NULL, 54.9, 0, false),
  ('OLEO DE SOJA 900ML', 'Alimentos', NULL, 5.99, 0, true),
  ('SAQUINHOS DE PIPOCA CAIXA COM 500', 'Descartáveis', NULL, 23.9, 0, false),
  ('SAL', 'Alimentos', NULL, 2.05, 0, true),
  ('SUCO FRUT SHOTT  150ML UVA', 'Bebidas', NULL, 1.69, 27, true),
  ('BALA DE GOMA SORTIDAS TIPO JUJUBA 1 KG', 'Ministerial', NULL, 15.99, 2, false),
  ('CAMISAS PARA BATISMO P (PRETA)', 'Ministerial', NULL, 32.99, 0, false),
  ('CAMISAS PARA BATISMO M (PRETA)', 'Ministerial', NULL, 32.99, 0, false),
  ('CAMISAS PARA BATISMO G (PRETA)', 'Ministerial', NULL, 32.99, 0, false),
  ('CAMISAS PARA BATISMO GG (PRETA)', 'Ministerial', NULL, 32.99, 0, false),
  ('CHAVEIRO COM QR-CODE', 'Ministerial', NULL, 15, 0, false),
  ('EVAGELHO DE JOÃO PERSONALIZADO', 'Ministerial', NULL, 1, 0, false),
  ('LIVRETO HISTORIA DE JESUS', 'Ministerial', NULL, 0, 0, false),
  ('LIVRETO OLHA A CBRIO', 'Ministerial', NULL, 0, 0, false),
  ('PENTES PARA BATISMO', 'Ministerial', NULL, 0, 0, false),
  ('SACO STAND UP POUTH COM ADESIVOS', 'Ministerial', NULL, 1.50399, 0, false),
  ('SACOLAS PERSONALIZADA', 'Ministerial', NULL, 0, 0, false),
  ('SEMENTE', 'Ministerial', NULL, 0, 0, false),
  ('SHORT MASCULINO P (PRETO)', 'Ministerial', NULL, 14.45, 0, false),
  ('SHORT MASCULINO M (PRETO)', 'Ministerial', NULL, 14.45, 0, false),
  ('SHORT MASCULINO G (PRETO)', 'Ministerial', NULL, 14.45, 0, false),
  ('SHORT MASCULINO GG (PRETO)', 'Ministerial', NULL, 14.45, 0, false),
  ('TOALHA PARA BATISMO', 'Ministerial', NULL, 34, 0, false),
  ('TOP P', 'Ministerial', NULL, 17.5, 0, false),
  ('TOP M', 'Ministerial', NULL, 17.5, 0, false),
  ('TOP G', 'Ministerial', NULL, 17.5, 0, false),
  ('TOP GG', 'Ministerial', NULL, 17.5, 0, false),
  ('COLHER DESCARTÁVEL PACOTE COM 50 UND', 'Descartáveis', NULL, 6.38, 5, false),
  ('FACA DESCARTÁVEL PACOTE COM 50 UND', 'Descartáveis', NULL, 10.7, 0, false),
  ('GARFO DESCARTÁVEL  PACOTE COM 50 UND', 'Descartáveis', NULL, 9.99, 0, false),
  ('PRATO PARA REFEIÇÕES DESCARTÁVEL  PACOTE COM 10 UND', 'Descartáveis', NULL, 7.5, 0, false),
  ('PRATO PARA SOBREMESA DESCARTÁVEL PACOTE COM 10 UND', 'Descartáveis', NULL, 1.92, 5, false),
  ('PRATO PARA SOPA DESCARTÁVEL  PACOTE COM 10 UND', 'Descartáveis', NULL, 2.08, 0, false),
  ('COCA COLA NATURAL 200ML FARDO COM 12 UND', 'Bebidas', NULL, 2.29, 3, true),
  ('COCA COLA ZERO 200ML FARDO COM 12 UND', 'Bebidas', NULL, 1.99, 5, true),
  ('MATE LEÃO 200ML FARDO COM 12 UND', 'Bebidas', NULL, 40.2, 0, true),
  ('SUCO DE LARANJA ONE NATURAL 180ML FARDO COM 6 UND', 'Bebidas', NULL, 4.59, 3, true),
  ('SUCO DE UVA ONE NATURAL 180ML FARDO COM 6 UND', 'Bebidas', NULL, 4.59, 5, true),
  ('SUCO DEL VALLE 200ML LARANLA', 'Bebidas', NULL, 1.39, 0, true),
  ('SUCO DEL VALLE 200ML UVA', 'Bebidas', NULL, 2.98, 0, true),
  ('ÁGUA MINERAL COPINHO 200ML CX COM 48 UND', 'Bebidas', NULL, 0.89, 0, true),
  ('ÁLCOOL LÍQUIDO 70° GALÃO 5LTS', 'Limpeza', NULL, 41.99, 2, false),
  ('CIF  450ML', 'Limpeza', NULL, 14.38, 5, false),
  ('CLORO HIPOCLORITO DE SÓDIO 1% GALÃO 5LTS', 'Limpeza', NULL, 9, 3, false),
  ('CAIXA DE COPO 200ml DESCARTÁVEL BRANCO COM 2.500 UND', 'Descartáveis', NULL, 130, 3, false),
  ('CAIXA DE COPO 80ml DESCARTÁVEL BRANCO CAIXA COM 2.500 UND', 'Descartáveis', NULL, 150, 1, false),
  ('DESINFETANTE GALÃO 5LTS', 'Limpeza', NULL, 11.15, 4, false),
  ('DETERGENTE GALÃO 5LTS', 'Limpeza', NULL, 25.82, 1, false),
  ('BACTERICIDA GALÃO 5LTS', 'Limpeza', NULL, 79.36, 1, false),
  ('ESPONJA DUPLA FACE 75X100MM (Lava louça)', 'Limpeza', NULL, 0.67, 5, false),
  ('AROMATIZADOR FINALIZADOR  FINISSHERFRESH BOUQUET 5 L', 'Limpeza', NULL, 138.62, 1, false),
  ('FLANELA BRANCA 48CMX68CM', 'Limpeza', NULL, 2.99, 5, false),
  ('GUARDANAPO 22X23 FLORAX PRATIC', 'Descartáveis', NULL, 1.36, 20, false),
  ('PANO DE CHÃO  48CMX68', 'Limpeza', NULL, 3.28, 40, false),
  ('PAPEL HIGIÉNICO INTERFOLHADO FOLHA DUPLA 9,6CMX20,5CM CX COM 32 PACOTE', 'Limpeza', NULL, 114.26, 1, false),
  ('PAPEL HIGIÉNICO ROLÃO FARDO COM 8 UND', 'Limpeza', NULL, 142.18, 1, false),
  ('PAPEL TOALHA INTERFOLHADO INOVATTA FT 22X21,4CM CAIXA COM 10 UND', 'Limpeza', NULL, 185.99, 6, false),
  ('REFIL AROMATIZADORES DE AMBIENTE GRIFES 5L', 'Limpeza', NULL, 289.71, 1, false),
  ('ROLO DE PERFEX', 'Limpeza', NULL, 78.75, 1, false),
  ('SABÃO EM PÓ 800G', 'Limpeza', NULL, 6.7, 2, false),
  ('SABONETE EM ESPUMA GALÃO 5LTS', 'Limpeza', NULL, 40.25, 1, false),
  ('SACO DE LIXO PRETO 20LTS PACOTE COM 100 UND', 'Limpeza', NULL, 7.99, 2, false),
  ('SACO DE LIXO PRETO 40LTS PACOTE COM 100 UND', 'Limpeza', NULL, 12.99, 2, false),
  ('SACO DE LIXO PRETO 60LTS PACOTE COM 100 UND', 'Limpeza', NULL, 26.11, 2, false),
  ('SACO DE LIXO PRETO 100LTS PACOTE COM 100 UND', 'Limpeza', NULL, 50.59, 2, false),
  ('SACO DE LIXO PRETO 200LTS PACOTE COM 100 UND', 'Limpeza', NULL, 89.28, 1, false),
  ('VEJA DESENGORDURANTE 500LM', 'Limpeza', NULL, 14.61, 4, false),
  ('VEJA LIMPEZA PESADA 500LM', 'Limpeza', NULL, 10.98, 4, false),
  ('VEJA LIMPA VIDRO 500LM', 'Limpeza', NULL, 18.99, 1, false),
  ('VEJA MULTIUSO 500LM', 'Limpeza', NULL, 4.49, 4, false),
  ('BATERIA V9', 'Papelaria', NULL, 0, 0, false),
  ('CANETA AZUL CAIXA COM 50', 'Papelaria', NULL, 0, 0, false),
  ('CANETA VERMELHA CAIXA COM 50', 'Papelaria', NULL, 0, 0, false),
  ('CANETA PRETA CAIXA COM 50', 'Papelaria', NULL, 0, 0, false),
  ('ENVELOPE AMARELO A4 PACOTE COM 50 UND', 'Papelaria', NULL, 0, 0, false),
  ('ENVELOPE BRANCO 24X33MM PACOTE COM 50 UND', 'Papelaria', NULL, 0, 0, false),
  ('ENVELOPE BRANCO 18X25MM PACOTE COM 50 UND', 'Papelaria', NULL, 0, 0, false),
  ('ENVELOPE PARA DÍZIMO E OFERTA PACOTE COM 400 UND', 'Papelaria', NULL, 0, 0, false),
  ('ENVELOPE PARDO PALEL A3', 'Papelaria', NULL, 0, 0, false),
  ('ENVELOPE PARDO PALEL A4', 'Papelaria', NULL, 0, 0, false),
  ('ENVELOPE PLÁSTICO 240X320MM', 'Papelaria', NULL, 0, 0, false),
  ('ESPIRAL WIRE 1.1/8 BRANCO A4 CAIXA COM 50 UND', 'Papelaria', NULL, 0, 0, false),
  ('FITA CREPE DUPLA FACE TRANSPARENTE 18MMX30M', 'Papelaria', NULL, 0, 0, false),
  ('FITA CREPE DUPLA FACE TRANSPARENTE 24MMX30M', 'Papelaria', NULL, 0, 0, false),
  ('FITA DUREX 12MMX10M', 'Papelaria', NULL, 0, 0, false),
  ('FITA DUREX 45MMX50M', 'Papelaria', NULL, 0, 0, false),
  ('FITA EMPACOTAMENTO FRAFT 45X45MM', 'Papelaria', NULL, 0, 0, false),
  ('GRAMPO 106/6 CAIXA COM 300G', 'Papelaria', NULL, 0, 0, false),
  ('GRAMPO 26/6 CAIXA COM 5.000', 'Papelaria', NULL, 0, 0, false),
  ('PAPEL A3-90 297MMX420MM PACOTE COM 500 FOLHAS', 'Papelaria', NULL, 0, 0, false),
  ('PAPEL  A4-75 210MMX297MM PACOTE COM 500 FOLHAS', 'Papelaria', NULL, 28.9, 2, false),
  ('PAPEL VERGER 180G FLS FILIPAPER COM 50 FOLHAS', 'Papelaria', NULL, 0, 0, false),
  ('PILHA ALCALINA DURACELL AA COM 16 UND', 'Papelaria', NULL, 0, 0, false),
  ('PILHA ALCALINA DURACELL AAA COM 2 UND PALITO', 'Papelaria', NULL, 0, 0, false),
  ('FITA ISOLANTE', 'Infra', 'Elétrico', 6.19, 6, false),
  ('FITA CREPE PEQUENA', 'Infra', 'Pintura', 6.9, 2, false),
  ('FITA CREPE GRANDE', 'Infra', 'Pintura', 13.9, 2, false),
  ('TINTA SUVINIL PISO - PRETO 18L', 'Infra', 'Pintura', 314, 1, false),
  ('TINTA SUVINIL FOSCO AREIA 18 L', 'Infra', 'Pintura', 325, 1, false),
  ('TINTA SUVINIL BRANCO NEVE FOSCO 18L', 'Infra', 'Pintura', 399.9, 1, false),
  ('TINTA CORAL  CINZA 18L', 'Infra', 'Pintura', 299, 1, false),
  ('P.U', 'Infra', 'Mat. Const.', 69.8, 2, false),
  ('TINTA SPRAY PRETO FOSCO', 'Infra', 'Pintura', 22, 3, false),
  ('TINTA SPRAY PRETO BRILHOSO', 'Infra', 'Pintura', 18.6, 3, false),
  ('LÂMPADA REDONDA 18W 6500K', 'Infra', 'Elétrico', 13.5, 5, false),
  ('LÂMPADA QUADRADA 18W 6500K', 'Infra', 'Elétrico', 15.5, 5, false),
  ('LÂMPADA REDONDA 18W 3000K', 'Infra', 'Elétrico', 18.8, 3, false),
  ('LÂMPADA REDONDA 24W 6500K', 'Infra', 'Elétrico', 25.04, 5, false),
  ('LÂMPADA QUADRADA 24W 6500K', 'Infra', 'Elétrico', 25.04, 5, false),
  ('LÂMPADA REFLETOR 50W 6500K', 'Infra', 'Elétrico', 29, 2, false),
  ('LÂMPADA REFLETOR 100W 6500K', 'Infra', 'Elétrico', 56.91, 1, false),
  ('LÂMPADA LED 12W 3000K', 'Infra', 'Elétrico', 6.7, 3, false),
  ('CABO PP 3VIAS 2,5  A METRO', 'Infra', 'Elétrico', 8.8, 20, false),
  ('IBERÊ MASSA PRETO', 'Infra', 'Mat. Const.', 19.99, 2, false),
  ('XADREZ CORANTE PRETO', 'Infra', 'Pintura', 7.99, 1, false),
  ('FITA BRANCA PVC 10M', NULL, 'Refrigeração', 6, 15, false),
  ('UNIÃO DE ACESSO 1/2', 'Infra', 'Refrigeração', 30, 1, false),
  ('UNIÃO DE ACESSO 3/8', 'Infra', 'Refrigeração', 25, 1, false),
  ('OLEO LUBRIFICANTE ISO VG4', 'Infra', 'Mat. Const.', 33, 1, false),
  ('BETUMADEIRA CABO PVC 10 CM', 'Infra', 'Mat. Const.', 13.9, 1, false),
  ('FITA VEDA ROSCA', 'Infra', 'Hidráulico', 15.9, 1, false),
  ('GRAXA  GRANDE 400GR', 'Infra', 'Mat. Const.', 29.9, 1, false),
  ('JOELHO 45° SOLDAVEL 25MM', 'Infra', 'Hidráulico', 2.5, 10, false),
  ('JOELHO 90° SOLDAVEL 25MM', 'Infra', 'Hidráulico', 10, 4, false),
  ('LAPIS CARPINTEIRO', 'Infra', 'Mat. Const.', 2.95, 4, false),
  ('LUVA SOLDAVEL 25MM', 'Infra', 'Hidráulico', 0.9, 10, false),
  ('PASSA FIO ALMA DE AÇO 20 M', 'Infra', 'Elétrico', 39.9, 1, false),
  ('ROLO ESPUMA AMARELO 15 CM TIGRE', 'Infra', 'Pintura', 9.9, 1, false),
  ('ROLO DE ESPUMA AMARELO 5 CM TIGRE', 'Infra', 'Pintura', 5.9, 1, false),
  ('ROLO D EESPUMA AMARELO 9 CM TIGRE', 'Infra', 'Pintura', 6.5, 1, false),
  ('ROLO DE LÃ ANTI GOTA 23CM COM CABO', 'Infra', 'Pintura', 26.9, 1, false),
  ('ROLO DE LÃ CARNEIRO 9 CM', 'Infra', 'Pintura', 10, 2, false),
  ('ROLO DE LÃ CARNEIRO 23CM', 'Infra', 'Pintura', 66.9, 4, false),
  ('ROLO TEXTURA FINA 23CM', 'Infra', 'Pintura', 27.9, 2, false),
  ('ROLO TEXTURA MEDIA', 'Infra', 'Pintura', 62.9, 1, false),
  ('SPRAY ANTIFERRUGEM WD 40', 'Infra', 'Pintura', 49.9, 1, false),
  ('TE 90° SOLDAVEL 25MM', 'Infra', 'Hidráulico', 1.85, 3, false),
  ('TRINCHA 1/2 POL TIGRE', 'Infra', 'Pintura', 3.35, 1, false),
  ('TRINCHA 2 POL TIGRE', 'Infra', 'Pintura', 8.75, 3, false),
  ('TRINCHA 3 POL TIGRE', 'Infra', 'Pintura', 16.9, 1, false),
  ('TUBO PVC SOLDAVEL 25MM', 'Infra', 'Hidráulico', 4.09, 1, false),
  ('MASCARA RESPIRADORA C/VALV.', 'Infra', 'Ferramenta', 1.36, 3, false),
  ('PARAFUSO 7mm', 'Infra', 'Mat. Const.', 32, 50, false),
  ('BUCHA PAREDE 6MM', 'Infra', 'Mat. Const.', 0.18, 50, false),
  ('OCULOS SEGURANÇA INCOLOR', 'Infra', 'Ferramenta', 4.5, 1, false),
  ('ADAPTADOR SOLDAVEL 25MM', 'Infra', 'Hidráulico', 2.67, 1, false),
  ('PARAFUSO 8MM', 'Infra', 'Mat. Const.', 0.45, 50, false),
  ('BUCHA PARA PAREDE 8MM', 'Infra', 'Mat. Const.', 0.1, 50, false),
  ('VALVULA ESPERIAL 3/4', 'Infra', 'Hidráulico', 32.9, 1, false),
  ('LIXA PARA PAREDE/MASSA', 'Infra', 'Pintura', 79, 10, false),
  ('LAMINA PARA ESTILETE 18MM', 'Infra', 'Ferramenta', 3.9, 1, false),
  ('BUCHA PARA PAREDE 10MM', 'Infra', 'Mat. Const.', 0.55, 50, false),
  ('PARAFUSO EM L 6MM', 'Infra', 'Mat. Const.', 0.65, 50, false),
  ('ESTILETE 18MM', 'Infra', 'Ferramenta', 14.99, 1, false),
  ('TEXTURA CIMENTO QUEIMADO CORAL', 'Infra', 'Pintura', 194.9, 1, false),
  ('PARAFUSO GANCHO 6MM', 'Infra', 'Mat. Const.', 1.27, 50, false),
  ('PARAFUSO TIPO L 8MM', 'Infra', 'Mat. Const.', 0.57, 50, false),
  ('PARAFUSO 12MM', 'Infra', 'Mat. Const.', 0.8, 50, false),
  ('ARRUELA 6MM', 'Infra', 'Mat. Const.', 0.37, 10, false),
  ('GESSO BRANCO KG', 'Infra', 'Mat. Const.', 15.5, 2, false),
  ('PARAFUSO DRYWALL 6MM', 'Infra', 'Mat. Const.', 0.35, 50, false),
  ('DISCO DE CORTE FERRO/METAL', 'Infra', 'Mat. Const.', 2.69, 20, false),
  ('PARAFUSO DRYWALL 8MM', 'Infra', 'Mat. Const.', 0.44, 50, false),
  ('TALHADEIRA PARA FURADEIRA', 'Infra', 'Ferramenta', 25.9, 1, false),
  ('PARAFUSO DRYWALL 10MM', 'Infra', 'Mat. Const.', 0.6, 50, false),
  ('ARRUELA 8MM', 'Infra', 'Mat. Const.', 0.52, 20, false),
  ('PARAFUSO MINI 2MM', 'Infra', 'Mat. Const.', 0.18, 50, false),
  ('INTERRUPTOR 10A 4X2', 'Infra', 'Elétrico', 6.49, 1, false),
  ('PONTEIRA PARA FURADEIRA', 'Infra', 'Ferramenta', 25.9, 1, false),
  ('MASSA CORRIDA SUVINIL 25KG', 'Infra', 'Mat. Const.', 109, 1, false),
  ('MASSA GRAUTE 20KG', 'Infra', 'Mat. Const.', 43.9, 1, false),
  ('MASSA PARA MADEIRA F12 IPE 1.6kg', NULL, NULL, 49.9, 1, false),
  ('TERMINAL CONECTOR PINO 2,5MM', 'Infra', 'Elétrico', 2.37, 20, false),
  ('CONECTOR EMENDA 2 POLOS 40A', NULL, NULL, 2.33, 10, false),
  ('CONECTOR VAGO EMENDA 2 4MM', 'Infra', 'Elétrico', 2.33, 50, false),
  ('TERMINAL TUBULAR SIMPLES 2,5MM', NULL, NULL, 2.15, 10, false),
  ('CONECTOR VAGO 3 EMENDAOS 4MM', 'Infra', 'Elétrico', 0.94, 50, false),
  ('TERMINAL FORQUILHA 2.5MM', 'Infra', 'Elétrico', 0.41, 20, false),
  ('BUCHA PARA DRYWALL BAILARINA', 'Infra', 'Mat. Const.', 0.15, 10, false),
  ('JOGO DE ESCOVA PARA FURADEIRA', 'Infra', 'Ferramenta', 39.99, 1, false),
  ('ABRAÇADEIRA ENCAIXE DE CANO PVC', 'Infra', 'Hidráulico', 9.5, 5, false),
  ('LUVA DE PROTEÇÃO PANO', 'Infra', 'Hidráulico', 4.29, 2, false),
  ('LUVA PROTEÇÃO PVC', 'Infra', 'Hidráulico', 14.99, 1, false),
  ('TORNEIRA DE COZINHA GOURMET', 'Infra', 'Hidráulico', 379.99, 1, false),
  ('ABRAÇADEIRA DE NYLON MÉDIA', 'Infra', 'Mat. Const.', 2.8, 20, false),
  ('LAMPADA LED 9W 4000K', 'Infra', 'Elétrico', 7.9, 5, false),
  ('LAMPADA TUBULAR LED 18W 4000K', 'Infra', 'Elétrico', 21.9, 5, false),
  ('LAMPADA SPOT QUADRADA 3W 6500K', 'Infra', 'Elétrico', 12.9, 5, false),
  ('ROLO DE FIO 1X2,5MM AZUL', 'Infra', 'Pintura', 280, 1, false),
  ('ROLO DE FIO 1X2,5MM PRETO', 'Infra', 'Elétrico', 280, 1, false),
  ('ROLO DE FIO 1X2,5MM VERMELHO', 'Infra', 'Elétrico', 280, 1, false),
  ('Painel Led Quadrada Branca Morna 18W 3000K', 'Infra', 'Elétrico', 39.9, 5, false),
  ('VEJA LIMPA ALUMÍNIO', 'Limpeza', NULL, 3.69, 2, false),
  ('ESPONJA DE AÇO BOMBRIL', 'Limpeza', NULL, 2.69, 2, false),
  ('LUSTRA MOVEIS 500ML', 'Limpeza', NULL, 8.3, 3, false),
  ('DISJUNTOR BIPOLAR 32A STECK', 'Infra', 'Elétrico', 42, 1, false),
  ('DISJUNTOR MONOPOLAR 32A', 'Infra', 'Elétrico', 21, 1, false),
  ('Isqueiro Big', NULL, NULL, 6.99, 5, false),
  ('TINTA SPRAY BRANCO FOSCO', NULL, NULL, 19.9, 1, false),
  ('BORRIFADOR SPRAY', 'Limpeza', NULL, 20.5, 2, false),
  ('VASSOURA GARY', 'Limpeza', NULL, 11.22, 1, false),
  ('BALDE PLASTICO 20 LITROS', 'Limpeza', NULL, 33, 2, false),
  ('ROLO FIO 1 X 6mm', 'Infra', NULL, 450, 1, false),
  ('DESINFETANTE LYSOFORM 1LITRO', 'Limpeza', NULL, 15, 2, false),
  ('ESPAGUETE BOIA PISCINA', 'Ministerial', NULL, 3.99, 5, false),
  ('BUCHA PAREDE 7MM', 'Infra', NULL, 0.5, 50, false),
  ('BUCHA PAREDE 12MM', 'Infra', NULL, 0.5, 50, false),
  ('TINTA CINZA ELEFANTE SUVINIL 18L', 'Infra', NULL, 254, 1, false),
  ('AGUARRAS 5 L', 'Infra', NULL, 105, 1, false),
  ('ESTOPA', 'Infra', NULL, 20, 3, false),
  ('THINNER 5L', 'Infra', NULL, 20, 1, false),
  ('FITA ANTI DERRAPANTE', 'Infra', NULL, 85, 0, false),
  ('COLA 85G', 'Infra', NULL, 18, 1, false),
  ('GÁS REFRIGERANTE 410A DE 11KG', 'Infra', NULL, 800, 2, false),
  ('GÁS REFRIGERANTE R32 9KG', 'Infra', NULL, 850, 2, false),
  ('GÁS REFRIGERANTE R22 11KG', 'Infra', NULL, 700, 2, false),
  ('GÁS NITROGÊNIO 12KG', 'Infra', NULL, 80, 1, false),
  ('FITA TERMICA PRATEADA', 'Infra', NULL, 15, 10, false),
  ('GÁS DE MAÇARICO DA MAP 400G', 'Infra', NULL, 100, 2, false),
  ('EMENDA DE 1/4', 'Infra', NULL, 5, 2, false),
  ('EMENDA DE 3/8', 'Infra', NULL, 5, 2, false),
  ('EMENDA DE 1/2', 'Infra', NULL, 5, 2, false),
  ('EMENDA DE 5/8', 'Infra', NULL, 5, 2, false),
  ('MIP DE REDUÇÃO 3/8 PARA 1/4', 'Infra', NULL, 5, 2, false),
  ('MIP DE REDUÇÃO 1/2 PARA 5/8', 'Infra', NULL, 5, 2, false),
  ('FORTE PLUS LIMPEZA', 'Infra', NULL, 5, 0, false),
  ('LAMPADA REDONDA 12W AVANT 6500K', 'Infra', NULL, 35, 2, false),
  ('FITA DUPLA FACE', 'Infra', NULL, 15.99, 4, false),
  ('MARTELO PICADEIRO SOLDADOR', 'Infra', NULL, 30, 1, false),
  ('AVENTAL PARA SOLDA', 'Infra', NULL, 24.99, 1, false),
  ('LUVA DE SOLDADOR', 'Infra', NULL, 10.99, 1, false),
  ('DISCO FLAP .60 METAL', 'Infra', NULL, 10.99, 1, false),
  ('ROLO DE LÃ CARNEIRO 15CM', 'Infra', NULL, 9.99, 1, false),
  ('PINCEL 2.5CM', 'Infra', NULL, 7.99, 2, false),
  ('PINCEL 3´', 'Infra', NULL, 7.99, 2, false),
  ('PINCEL 2,5´', 'Infra', NULL, 5.99, 2, false),
  ('PINCEL 4´', 'Infra', NULL, 8.99, 2, false),
  ('PARAFUSO DE DRYWALL 3.5 X35', 'Infra', NULL, 0.3, 100, false),
  ('VASSOURA DE PELO SINTÉTICO', 'Limpeza', NULL, 30.2, 4, false),
  ('PANO DE PRATO ALGODÃO', 'Limpeza', NULL, 5.2, 10, false),
  ('FLOTADOR LIMPA CARPETE', NULL, NULL, 125, 1, false),
  ('AROMATIZANTE CHÁ BRANCO', 'Limpeza', NULL, 26.5, 2, false),
  ('ALCOOL ISOPROPILICO', NULL, NULL, 11.7, 2, false),
  ('LIMPADOR MULT FLOTADOR 5 LITROS', 'Limpeza', NULL, 47.85, 1, false),
  ('DESENGORDURANTE 5 LITROS CORDEX', 'Limpeza', NULL, 31.35, 1, false),
  ('LUVA PARA LIMPEZA', 'Limpeza', NULL, 4.99, 1, false),
  ('LIMPA PISO LAMINADO', 'Limpeza', NULL, 11.9, 2, false),
  ('BACTERICIDA 1,5 LITROS', NULL, NULL, 30.99, 2, false),
  ('SAL LIQUIDO', 'Ministerial', NULL, 12.5, 1, false)
ON CONFLICT (lower(btrim(nome))) DO NOTHING;
COMMIT;
